### PR TITLE
DAB Docs changes for `dab configure [options] [value]` command to update RuntimeConfig sections

### PR DESCRIPTION
**Pull request by sezal98**
These changes are with respect to the new command that has been added in DAB
`dab configure [options] [value]`
These changes include modifications made for Datasource and Runtime sections of the config. 
This command is newly added to modify the config for sections other than entities as we already have a `dab update` command for that.

### CODE REVIEW

**Comment by Court72** [comment]
@sezal98,

When you're ready for this PR to be reviewed, take it out of **Draft** by selecting **Ready for review**.

image

**Comment by Court72** [comment]
@seesharprun,

When the PR is ready for review, can you review the proposed changes? 
	
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 
	
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by sezal98** [comment]
#sign-off
@MicrosoftDocs/public-repo-pr-review-team

**Comment by v-dirichards** [comment]
@seesharprun  When the PR is ready for review, can you review the proposed changes?

Important: When the changes are ready for publication, adding a #sign-off comment is the best way to signal that the PR is ready for the review team to merge.

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by seesharprun — APPROVED** [review]

**Comment by seesharprun** [comment]
#sign-off

**Pull request merged**
