### PR TITLE
fixing accidental reversion of https://github.com/MicrosoftDocs/data-api-builder-docs/pull/18

### PR DESCRIPTION
**Pull request by Jak-MS**
fixing accidental reversion of https://github.com/MicrosoftDocs/data-api-builder-docs/pull/18

@seesharprun @seantleonard

### CODE REVIEW

**Comment by Jak-MS** [comment]
@seantleonard - check that these are the same changes you were making in the other PR

**Comment by Jak-MS** [comment]
Can you review the proposed changes and tag me?

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by seantleonard — APPROVED** [review]

**Comment by seantleonard** [comment]
@jak-ms , approved! thanks for getting this in

**Comment by abhishekkumams** [comment]
@Jak-MS , when do these changes publish ?

**Comment by Jak-MS** [comment]
@abhishekkumams - the commits just sync'd with the private repo, and should get published later today.

**Comment by Jak-MS** [comment]
the sync pr was stuck for some reason so i merged it

**Pull request merged**
